#!/usr/bin/env bash
# Create the muzikoo role + muzikoo_api database, then write .env with the
# credentials.
#
# Needs a PostgreSQL superuser once. Provide its password via PGPASSWORD:
#
#   PGPASSWORD='...' scripts/bootstrap_db.sh
#
# or, if your OS user can reach the socket as postgres:
#
#   sudo -u postgres scripts/bootstrap_db.sh --peer
#
# Idempotent: re-running resets the app role's password and rewrites .env.

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

APP_DB="${APP_DB:-muzikoo_api}"
APP_USER="${APP_USER:-muzikoo}"
SUPERUSER="${SUPERUSER:-postgres}"
PGHOST_="${PGHOST_:-localhost}"
PGPORT_="${PGPORT_:-5432}"

# Reuse the password and API key already in .env so re-running does not
# invalidate credentials that clients are already using.
if [[ -f .env ]]; then
    : "${APP_PASSWORD:=$(sed -n 's/^DB_PASSWORD=//p' .env | head -1)}"
    : "${API_KEYS:=$(sed -n 's/^API_KEYS=//p' .env | head -1)}"
fi
if [[ -z "${APP_PASSWORD:-}" ]]; then
    APP_PASSWORD="$(python3 -c 'import secrets; print(secrets.token_urlsafe(24))')"
fi
if [[ -z "${API_KEYS:-}" ]]; then
    API_KEYS="$(python3 -c 'import secrets; print(secrets.token_urlsafe(24))')"
fi

PSQL_CONN=(-h "$PGHOST_" -p "$PGPORT_" -U "$SUPERUSER")
if [[ "${1:-}" == "--peer" ]]; then
    PSQL_CONN=()   # local socket, peer auth
fi

echo ">> creating role '$APP_USER' and database '$APP_DB' ..."
psql "${PSQL_CONN[@]}" -d postgres -q -v ON_ERROR_STOP=1 \
     -v app_user="$APP_USER" \
     -v app_password="$APP_PASSWORD" \
     -v app_db="$APP_DB" \
     -f sql/000_bootstrap.sql

echo ">> writing .env"
cat > .env <<EOF
# Generated by scripts/bootstrap_db.sh on $(date -Iseconds)
DB_HOST=$PGHOST_
DB_PORT=$PGPORT_
DB_NAME=$APP_DB
DB_USER=$APP_USER
DB_PASSWORD=$APP_PASSWORD

DATASET_PATH=data/dataset.json
CHUNK_SIZE=5000
MODEL_PATH=models/knn_model.joblib

DEFAULT_LIMIT=50
MAX_LIMIT=200
CORS_ORIGINS=
API_KEYS=$API_KEYS
EOF
chmod 600 .env

echo ">> verifying the app role can connect"
PGPASSWORD="$APP_PASSWORD" psql -h "$PGHOST_" -p "$PGPORT_" -U "$APP_USER" -d "$APP_DB" \
    -qtAc "select 'connected as ' || current_user || ' to ' || current_database()"

echo ">> API key (send as ?api_key=... on every /v1 request): $API_KEYS"
echo ">> done. next: make db-init && make db-load && make db-index && make train"
